
use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `BitwardenSecret` resource, directly
/// reflects context of the `echoes.example.com.yaml` file to be found in this repository.
/// The `BitwardenSecret` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
group = "tomjo.net",
version = "v1",
kind = "BitwardenSecret",
plural = "bitwardensecrets",
derive = "PartialEq",
namespaced
)]
pub struct BitwardenSecretSpec {
    pub type_: String,
    pub item: String,
}