name: Determine version
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      version:
        description: "Determined version"
        value: ${{ jobs.determine_version.outputs.version }}
jobs:
  determine_version:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: '0'
      - name: Set up Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: 1.21.3
      - name: Install SVU
        run: go install github.com/caarlos0/svu@00b733b056534c0fbdb316bbd37c023e7bb80905 #v1.11.0
      - name: Get branch name (merge)
        if: ${{ github.event_name != 'pull_request' && github.event_name != 'release' }}
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
      - name: Get branch name (pull request)
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV
      - name: Determine version (branch)
        if: ${{ env.BRANCH_NAME != 'master' }}
        run: 'echo "PROJECT_VERSION=$(svu --pre-release ${{ env.BRANCH_NAME }}-alpha.$(git rev-list origin/master.. --count))" >> "$GITHUB_ENV"'
      - name: Determine version (master)
        if: ${{ github.event_name != 'release' && env.BRANCH_NAME == 'master' }}
        run: 'echo "PROJECT_VERSION=$(svu)" >> "$GITHUB_ENV"'
      - name: Determine version (release)
        if: ${{ github.event_name == 'release' }}
        run: 'echo "PROJECT_VERSION=${{ github.event.release.tag_name }}" >> "$GITHUB_ENV"'
      - run: 'echo "Determined version: $PROJECT_VERSION"'
      - run: 'echo "PROJECT_VERSION=$PROJECT_VERSION" >> "$GITHUB_OUTPUT"'
        id: set-version
    outputs:
      version: ${{ steps.set-version.outputs.PROJECT_VERSION}}
